### ISSUE TITLE
'settings' should be immutable

### ISSUE THREAD

**Issue by mvila** [evert0n/koa-cors#21]
At the beginning of the middleware handler, there is:

```js
var options = settings || defaults;
```

Later, at several places, the `options` object is modified. For example:

```js
options.headers = this.header['access-control-request-headers'];
```

It means that the global middleware `settings` object (or `defaults` if no `settings` are specified) is modified from one request to another. I think it's dangerous and a source of bugs.

**Comment by evert0n** [comment]
Hey @mvila Thanks, this has been fixed with the PR #25
