### ISSUE TITLE
expose PATCH by default

### ISSUE THREAD

**Issue by solsend2l** [evert0n/koa-cors#27]
`methods: 'GET,HEAD,PUT,POST,DELETE,PATCH'`

**Comment by evert0n** [comment]
Hey @solsend2l  thanks for the request, but I'm not so sure that this a high common method used to make to the default list for that reason I'm adding at this time, you can allows setup for your use case, using the options.

**Comment by solsend2l** [comment]
It's your choice. But JSYK we got bit by this while using the Swagger API documentation/testing tool. It's a pretty common method IMHO. We are using the options object as a bypass, thanks.

**Comment by nathanboktae** [comment]
If the defaults are in the spirit of "Allow all the methods", then `PATCH` should be included by default too. How common patch is is a moving target.

I would like this PR reopened and accepted.

**Comment by azhang** [comment]
+1 issue should be reopened

**Comment by ztanner** [comment]
+1 -- also ran into this issue.

**Comment by fritx** [comment]
+999

**Comment by KyleCartmell** [comment]
+1
