### ISSUE TITLE
Hi, Does this project is still maintained?

### ISSUE THREAD

**Issue by sabakugaara** [evert0n/koa-cors#46]
I need this commit https://github.com/evert0n/koa-cors/commit/6b1e0024ab7bd1b7119a07538518c9d67d460cfd, but it is not published as a new version. 

If you need, I can help to maintain this repo @evert0n :)

**Comment by niftylettuce** [comment]
@sabakugaara please see <https://github.com/koajs/cors>

**Comment by sabakugaara** [comment]
thanks~
